version: '3'

# Before Using this:
#  docker network create LocalDevProxyNetwork
#

services:
  traefik:
    image: traefik:v2.2
    command:
      - --global.checkNewVersion=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=LocalDevProxyNetwork
      # this controls the automatic hostname rule creation
      # when traefik sees existing containers or new containers come up
      - --providers.docker.defaultRule=Host(`{{ .Name }}.dev.localhost`)
      - --log.level=INFO
      - --api
    ports:
      - "80:80"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.dev.localhost`)"

      - "traefik.http.routers.api.service=api@internal"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


networks:
  proxy:
    external:
      name: LocalDevProxyNetwork