---
awesome:
  theme: pro-dark
  gap: 20
rofi:
  powermenu:
    style: style-1
    theme: dracula
    type: type-2
  launcher:
    style: style-2
    theme: dracula
    type: type-3
  runner:
    style: style-1
    theme: dracula
    type: type-1
  switcher:
    style: style-1
    theme: dracula
    type: type-1
...
