---
awesome:
  theme: airtonix
  gap: 4
rofi:
  switcher:
    type: type-2
    theme: dracula
    style: style-1
  runner:
    type: type-2
    theme: dracula
    style: style-6
  launcher:
    type: type-3
    theme: dracula
    style: style-2
  powermenu:
    type: type-2
    theme: dracula
    style: style-1
...
