---
rofi:
  switcher:
    theme: dracula
    type: type-1
    style: style-1
  launcher:
    theme: dracula
    type: type-3
    style: style-2
  runner:
    theme: dracula
    type: type-1
    style: style-1
  powermenu:
    theme: dracula
    type: type-2
    style: style-1
awesome:
  theme: pro-dark
  gap: 20
...
