---
awesome:
  gap: 10
  theme: zenburn
  tag: 1

rofi:
  runner:
    style: style-1
    type: type-1
    theme: onedark
  launcher:
    style: style-2
    type: type-3
    theme: onedark
  switcher:
    style: style-1
    type: type-1
    theme: onedark
  powermenu:
    style: style-1
    type: type-1
    theme: onedark
