---
awesome:
  theme: airtonix
  gap: 4
rofi:
  powermenu:
    style: style-1
    type: type-2
    theme: dracula
  runner:
    style: style-6
    type: type-2
    theme: dracula
  launcher:
    style: style-2
    type: type-3
    theme: dracula
  switcher:
    style: style-1
    type: type-2
    theme: dracula
...
