---
rofi:
  powermenu:
    type: type-2
    theme: dracula
    style: style-1
  switcher:
    type: type-1
    theme: dracula
    style: style-1
  runner:
    type: type-1
    theme: dracula
    style: style-1
  launcher:
    type: type-3
    theme: dracula
    style: style-2
awesome:
  gap: 20
  theme: pro-dark
...
