---
awesome:
  theme: airtonix
  gap: 4
rofi:
  launcher:
    theme: dracula
    style: style-2
    type: type-3
  runner:
    theme: dracula
    style: style-6
    type: type-2
  switcher:
    theme: dracula
    style: style-1
    type: type-2
  powermenu:
    theme: dracula
    style: style-1
    type: type-2
...
