---
awesome:
  gap: 0
  tag: 1
  theme: zenburn

rofi:
  launcher:
    type: type-1
    style: style-1
    theme: onedark
  powermenu:
    type: type-1
    style: style-1
    theme: onedark
  switcher:
    type: type-1
    style: style-1
    theme: onedark
  runner:
    type: type-1
    style: style-1
    theme: onedark
