---
awesome:
  theme: pro-dark
  gap: 20
rofi:
  powermenu:
    style: style-1
    type: type-2
    theme: dracula
  launcher:
    style: style-2
    type: type-3
    theme: dracula
  runner:
    style: style-1
    type: type-1
    theme: dracula
  switcher:
    style: style-1
    type: type-1
    theme: dracula
...
