---
where: os.name == "linux" || os.name == "macosx"

actions:
 - action: file.copy
   from: ../../../profile/.tool-versions
   to: "{{user.home_dir}}/.tool-versions"

 - action: cmd.run
   command: bash
   args:
    - tools/asdf/setup.bash
